version: "3.9"
services:
 web:
  build: .
  working_dir: /data
  command: cadastro.py
  links:
    - db
  volumes:
    - .:/data
  ports:
    - "5000:5050"

 db:
  image: mysql:5.7
  environment:
      MYSQL_ROOT_PASSWORD: mudar123
  ports:
    - "3309:3309"